In [3]:
import pandas as pd
import numpy as np
import json

from pathlib import Path

In [4]:
PROJECT_ROOT = Path("..")

STATSBOMB_DIR = PROJECT_ROOT / "data" / "raw" / "statsbomb"
WORLDCUP_DB_DIR = PROJECT_ROOT / "data" / "raw" / "worldcup_db"

print(STATSBOMB_DIR)
print(WORLDCUP_DB_DIR)

..\data\raw\statsbomb
..\data\raw\worldcup_db

In [5]:
STATSBOMB_DATA = STATSBOMB_DIR / "data"

COMPETITIONS_PATH = STATSBOMB_DATA / "competitions.json"

MATCHES_DIR = STATSBOMB_DATA / "matches"
EVENTS_DIR = STATSBOMB_DATA / "events"
LINEUPS_DIR = STATSBOMB_DATA / "lineups"
THREESIXTY_DIR = STATSBOMB_DATA / "three-sixty"

In [6]:
competitions = pd.read_json(COMPETITIONS_PATH)


print(competitions.columns)
print(competitions.shape)
print(competitions.info())
competitions.head()

Index(['competition_id', 'season_id', 'country_name', 'competition_name',
       'competition_gender', 'competition_youth', 'competition_international',
       'season_name', 'match_updated', 'match_updated_360',
       'match_available_360', 'match_available'],
      dtype='str')
(80, 12)
<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             80 non-null     int64
 1   season_id                  80 non-null     int64
 2   country_name               80 non-null     str
 3   competition_name           80 non-null     str
 4   competition_gender         80 non-null     str
 5   competition_youth          80 non-null     bool
 6   competition_international  80 non-null     bool
 7   season_name                80 non-null     str
 8   match_updated              80 non-null     str
 9   match_updated_360          58 non-null     str
 10  match_available_360        12 non-null     str
 11  match_available            80 non-null     str
dtypes: bool(2), int64(2), str(8)
memory usage: 6.5 KB
None

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [7]:
competitions[
    ["competition_id",
     "competition_name",
     "season_id",
     "season_name"]
].head(20)

    competition_id        competition_name  season_id season_name
0                9           1. Bundesliga        281   2023/2024
1                9           1. Bundesliga         27   2015/2016
2             1267  African Cup of Nations        107        2023
3               16        Champions League          4   2018/2019
4               16        Champions League          1   2017/2018
5               16        Champions League          2   2016/2017
6               16        Champions League         27   2015/2016
7               16        Champions League         26   2014/2015
8               16        Champions League         25   2013/2014
9               16        Champions League         24   2012/2013
10              16        Champions League         23   2011/2012
11              16        Champions League         22   2010/2011
12              16        Champions League         21   2009/2010
13              16        Champions League         41   2008/2009
14              16        Champions League         39   2006/2007
15              16        Champions League         37   2004/2005
16              16        Champions League         44   2003/2004
17              16        Champions League         76   1999/2000
18              16        Champions League        277   1972/1973
19              16        Champions League         71   1971/1972

In [8]:
world_cups = competitions[
    competitions["competition_name"] == "FIFA World Cup"
]

world_cups[
    ["competition_id",
     "competition_name",
     "season_id",
     "season_name"]
]

    competition_id competition_name  season_id season_name
30              43   FIFA World Cup        106        2022
31              43   FIFA World Cup          3        2018
32              43   FIFA World Cup         55        1990
33              43   FIFA World Cup         54        1986
34              43   FIFA World Cup         51        1974
35              43   FIFA World Cup        272        1970
36              43   FIFA World Cup        270        1962
37              43   FIFA World Cup        269        1958

In [9]:
WC_COMPETITION_ID = 43
WC_2022_SEASON_ID = 106

matches_2022_path = MATCHES_DIR / str(WC_COMPETITION_ID) / f"{WC_2022_SEASON_ID}.json"

print(matches_2022_path)
print(matches_2022_path.exists())

..\data\raw\statsbomb\data\matches\43\106.json
True

In [10]:
matches_2022 = pd.read_json(matches_2022_path)

matches_2022.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,3857276,2022-12-01,15:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 1833, 'home_team_name': 'Cana...","{'away_team_id': 788, 'away_team_name': 'Moroc...",1,2,available,available,2026-05-04T01:46:04.664252,2026-05-04T01:50:33.318123,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000838, 'name': 'Al Thumama Stadium', ...","{'id': 2638, 'name': 'Raphael Claus', 'country..."
1,3857271,2022-11-21,13:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 768, 'home_team_name': 'Engla...","{'away_team_id': 797, 'away_team_name': 'Iran'...",6,2,available,available,2026-05-04T01:40:47.671394,2026-05-04T01:43:30.216315,"{'data_version': '1.1.0', 'shot_fidelity_versi...",1,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2638, 'name': 'Raphael Claus', 'country..."
2,3857296,2022-12-01,15:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 785, 'home_team_name': 'Croat...","{'away_team_id': 782, 'away_team_name': 'Belgi...",0,0,available,available,2026-05-04T01:44:02.255386,2026-05-04T01:50:06.343225,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000793, 'name': 'Ahmad bin Ali Stadium...","{'id': 8, 'name': 'Anthony Taylor', 'country':..."
3,3857274,2022-11-25,16:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 941, 'home_team_name': 'Nethe...","{'away_team_id': 3565, 'away_team_name': 'Ecua...",1,1,available,available,2026-05-04T01:43:00.444702,2026-05-04T01:50:07.646458,"{'data_version': '1.1.0', 'shot_fidelity_versi...",2,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2311, 'name': 'Mustapha Ghorbal', 'coun..."
4,3857255,2022-12-01,19:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 778, 'home_team_name': 'Japan...","{'away_team_id': 772, 'away_team_name': 'Spain...",2,1,available,available,2026-05-04T01:42:55.630428,2026-05-04T01:49:36.594944,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2366, 'name': 'Victor Miguel de Freitas..."

In [11]:
matches_2022.shape

(64, 18)

In [12]:
matches_2022.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'metadata',
       'match_week', 'competition_stage', 'stadium', 'referee'],
      dtype='str')

In [13]:
matches_2022[
    ["match_id", "match_date", "home_team", "away_team", "home_score", "away_score"]
].head()

,match_id,match_date,home_team,away_team,home_score,away_score
0,3857276,2022-12-01,"{'home_team_id': 1833, 'home_team_name': 'Cana...","{'away_team_id': 788, 'away_team_name': 'Moroc...",1,2
1,3857271,2022-11-21,"{'home_team_id': 768, 'home_team_name': 'Engla...","{'away_team_id': 797, 'away_team_name': 'Iran'...",6,2
2,3857296,2022-12-01,"{'home_team_id': 785, 'home_team_name': 'Croat...","{'away_team_id': 782, 'away_team_name': 'Belgi...",0,0
3,3857274,2022-11-25,"{'home_team_id': 941, 'home_team_name': 'Nethe...","{'away_team_id': 3565, 'away_team_name': 'Ecua...",1,1
4,3857255,2022-12-01,"{'home_team_id': 778, 'home_team_name': 'Japan...","{'away_team_id': 772, 'away_team_name': 'Spain...",2,1

In [14]:
matches_2022["home_team"].iloc[0]

{'home_team_id': 1833,
 'home_team_name': 'Canada',
 'home_team_gender': 'male',
 'home_team_group': 'F',
 'country': {'id': 40, 'name': 'Canada'},
 'managers': [{'id': 4435,
   'name': 'John Herdman',
   'nickname': None,
   'dob': '1975-07-19',
   'country': {'id': 68, 'name': 'England'}}]}

In [15]:
matches_2022["home_team_id"] = (matches_2022["home_team"].apply(lambda x: x["home_team_id"]))
matches_2022["home_team_name"] = (matches_2022["home_team"].apply(lambda x: x["home_team_name"]))
matches_2022["away_team_id"] = (matches_2022["away_team"].apply(lambda x: x["away_team_id"]))
matches_2022["away_team_name"] = (matches_2022["away_team"].apply(lambda x: x["away_team_name"]))

In [16]:
matches_2022.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,metadata,match_week,competition_stage,stadium,referee,home_team_id,home_team_name,away_team_id,away_team_name
0,3857276,2022-12-01,15:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 1833, 'home_team_name': 'Cana...","{'away_team_id': 788, 'away_team_name': 'Moroc...",1,2,available,...,2026-05-04T01:50:33.318123,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000838, 'name': 'Al Thumama Stadium', ...","{'id': 2638, 'name': 'Raphael Claus', 'country...",1833,Canada,788,Morocco
1,3857271,2022-11-21,13:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 768, 'home_team_name': 'Engla...","{'away_team_id': 797, 'away_team_name': 'Iran'...",6,2,available,...,2026-05-04T01:43:30.216315,"{'data_version': '1.1.0', 'shot_fidelity_versi...",1,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2638, 'name': 'Raphael Claus', 'country...",768,England,797,Iran
2,3857296,2022-12-01,15:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 785, 'home_team_name': 'Croat...","{'away_team_id': 782, 'away_team_name': 'Belgi...",0,0,available,...,2026-05-04T01:50:06.343225,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000793, 'name': 'Ahmad bin Ali Stadium...","{'id': 8, 'name': 'Anthony Taylor', 'country':...",785,Croatia,782,Belgium
3,3857274,2022-11-25,16:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 941, 'home_team_name': 'Nethe...","{'away_team_id': 3565, 'away_team_name': 'Ecua...",1,1,available,...,2026-05-04T01:50:07.646458,"{'data_version': '1.1.0', 'shot_fidelity_versi...",2,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2311, 'name': 'Mustapha Ghorbal', 'coun...",941,Netherlands,3565,Ecuador
4,3857255,2022-12-01,19:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 778, 'home_team_name': 'Japan...","{'away_team_id': 772, 'away_team_name': 'Spain...",2,1,available,...,2026-05-04T01:49:36.594944,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2366, 'name': 'Victor Miguel de Freitas...",778,Japan,772,Spain

In [17]:
teams_2022 = sorted(
    set(matches_2022["home_team_name"]) |
    set(matches_2022["away_team_name"])
)

print(len(teams_2022))
print(teams_2022)

32
['Argentina', 'Australia', 'Belgium', 'Brazil', 'Cameroon', 'Canada', 'Costa Rica', 'Croatia', 'Denmark', 'Ecuador', 'England', 'France', 'Germany', 'Ghana', 'Iran', 'Japan', 'Mexico', 'Morocco', 'Netherlands', 'Poland', 'Portugal', 'Qatar', 'Saudi Arabia', 'Senegal', 'Serbia', 'South Korea', 'Spain', 'Switzerland', 'Tunisia', 'United States', 'Uruguay', 'Wales']

## Investigo un match

In [18]:
match_id = 3857276

event_file = EVENTS_DIR / f"{match_id}.json"

print(event_file.exists())

True

In [19]:
import json

with open(event_file, "r", encoding="utf-8") as f:
    events = json.load(f)

In [20]:
print(type(events), len(events))

<class 'list'> 3388

In [21]:
from pprint import pprint

pprint(events[0])

{'duration': 0.0,
 'id': '1f60fe1e-0340-49e2-975e-f16f54c5da1a',
 'index': 1,
 'minute': 0,
 'period': 1,
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'possession': 1,
 'possession_team': {'id': 1833, 'name': 'Canada'},
 'second': 0,
 'tactics': {'formation': 4411,
             'lineup': [{'jersey_number': 18,
                         'player': {'id': 15958, 'name': 'Milan Borjan'},
                         'position': {'id': 1, 'name': 'Goalkeeper'}},
                        {'jersey_number': 2,
                         'player': {'id': 44703, 'name': 'Alistair Johnston'},
                         'position': {'id': 2, 'name': 'Right Back'}},
                        {'jersey_number': 5,
                         'player': {'id': 11846,
                                    'name': 'Steven de Sousa Vitoria'},
                         'position': {'id': 3, 'name': 'Right Center Back'}},
                        {'jersey_number': 4,
                         'player': {'id': 23828, 'name': 'Kamal Miller'},
                         'position': {'id': 5, 'name': 'Left Center Back'}},
                        {'jersey_number': 3,
                         'player': {'id': 29758, 'name': 'Sam Adekugbe'},
                         'position': {'id': 6, 'name': 'Left Back'}},
                        {'jersey_number': 21,
                         'player': {'id': 12770, 'name': 'Jonathan Osorio'},
                         'position': {'id': 9,
                                      'name': 'Right Defensive Midfield'}},
                        {'jersey_number': 14,
                         'player': {'id': 16252, 'name': 'Mark Anthony Kaye'},
                         'position': {'id': 11,
                                      'name': 'Left Defensive Midfield'}},
                        {'jersey_number': 19,
                         'player': {'id': 12365, 'name': 'Alphonso Davies'},
                         'position': {'id': 12, 'name': 'Right Midfield'}},
                        {'jersey_number': 11,
                         'player': {'id': 24024, 'name': 'Tajon Buchanan'},
                         'position': {'id': 16, 'name': 'Left Midfield'}},
                        {'jersey_number': 10,
                         'player': {'id': 9922, 'name': 'David Junior Hoilett'},
                         'position': {'id': 19,
                                      'name': 'Center Attacking Midfield'}},
                        {'jersey_number': 17,
                         'player': {'id': 16459, 'name': 'Cyle Larin'},
                         'position': {'id': 23, 'name': 'Center Forward'}}]},
 'team': {'id': 1833, 'name': 'Canada'},
 'timestamp': '00:00:00.000',
 'type': {'id': 35, 'name': 'Starting XI'}}

Veo el primer evento real

In [22]:
for event in events:
    if event["type"]["name"] != "Starting XI":
        print(event["type"]["name"])
        break

Half Start

In [23]:
counter = 0
for event in events:
    if event["type"]["name"] == "Pass":
        from pprint import pprint
        pprint(event)
        counter +=1
        if counter == 3:
            break

{'duration': 0.83469,
 'id': '05a57281-9295-408a-9c4f-e32d7fad4d96',
 'index': 5,
 'location': [61.0, 40.1],
 'minute': 0,
 'pass': {'angle': 3.045886,
          'body_part': {'id': 38, 'name': 'Left Foot'},
          'end_location': [48.5, 41.3],
          'height': {'id': 1, 'name': 'Ground Pass'},
          'length': 12.557467,
          'recipient': {'id': 5234, 'name': 'Sofyan Amrabat'},
          'type': {'id': 65, 'name': 'Kick Off'}},
 'period': 1,
 'play_pattern': {'id': 9, 'name': 'From Kick Off'},
 'player': {'id': 6301, 'name': 'Youssef En-Nesyri'},
 'position': {'id': 23, 'name': 'Center Forward'},
 'possession': 2,
 'possession_team': {'id': 788, 'name': 'Morocco'},
 'related_events': ['1267faf9-e033-4985-925a-2f9521d63bc0'],
 'second': 0,
 'team': {'id': 788, 'name': 'Morocco'},
 'timestamp': '00:00:00.460',
 'type': {'id': 30, 'name': 'Pass'}}
{'duration': 1.47092,
 'id': '3a06bcce-1408-4a0b-be01-f6b93f142b30',
 'index': 8,
 'location': [48.4, 42.5],
 'minute': 0,
 'pass': {'angle': 2.3968697,
          'body_part': {'id': 40, 'name': 'Right Foot'},
          'end_location': [30.5, 59.0],
          'height': {'id': 1, 'name': 'Ground Pass'},
          'length': 24.344608,
          'recipient': {'id': 12149, 'name': 'Nayef Aguerd'}},
 'period': 1,
 'play_pattern': {'id': 9, 'name': 'From Kick Off'},
 'player': {'id': 5234, 'name': 'Sofyan Amrabat'},
 'position': {'id': 10, 'name': 'Center Defensive Midfield'},
 'possession': 2,
 'possession_team': {'id': 788, 'name': 'Morocco'},
 'related_events': ['d9f8538d-a5cd-4ed6-8f04-bd8394133fb1'],
 'second': 2,
 'team': {'id': 788, 'name': 'Morocco'},
 'timestamp': '00:00:02.415',
 'type': {'id': 30, 'name': 'Pass'}}
{'duration': 2.262904,
 'id': '1f1b0ef8-1a1d-45b3-bf9c-4299ea836377',
 'index': 11,
 'location': [30.9, 59.0],
 'minute': 0,
 'pass': {'angle': -1.6050508,
          'body_part': {'id': 38, 'name': 'Left Foot'},
          'end_location': [29.8, 26.9],
          'height': {'id': 1, 'name': 'Ground Pass'},
          'length': 32.118843,
          'recipient': {'id': 5219, 'name': 'Romain Saïss'}},
 'period': 1,
 'play_pattern': {'id': 9, 'name': 'From Kick Off'},
 'player': {'id': 12149, 'name': 'Nayef Aguerd'},
 'position': {'id': 3, 'name': 'Right Center Back'},
 'possession': 2,
 'possession_team': {'id': 788, 'name': 'Morocco'},
 'related_events': ['9f6ff602-783e-4527-94d3-07e216ad29d9'],
 'second': 5,
 'team': {'id': 788, 'name': 'Morocco'},
 'timestamp': '00:00:05.143',
 'type': {'id': 30, 'name': 'Pass'}}

In [24]:
pass_events = []

for event in events:
    if event["type"]["name"] != "Pass":
        continue

    pass_data = event["pass"]

    pass_events.append({
        "match_id": match_id,
        "event_id": event["id"],
        "player_id": event["player"]["id"],
        "player_name": event["player"]["name"],
        "team_id": event["team"]["id"],
        "team_name": event["team"]["name"],
        "position": event["position"]["name"],
        "recipient_id": pass_data.get("recipient", {}).get("id"),
        "recipient_name": pass_data.get("recipient", {}).get("name"),
        "pass_length": pass_data.get("length"),
        "pass_angle": pass_data.get("angle"),
        "pass_height": pass_data.get("height", {}).get("name"),
        "pass_type": pass_data.get("type", {}).get("name"),
        "start_x": event["location"][0],
        "start_y": event["location"][1],
        "end_x": pass_data.get("end_location", [None, None])[0],
        "end_y": pass_data.get("end_location", [None, None])[1],
    })

passes_df = pd.DataFrame(pass_events)

passes_df.head()

,match_id,event_id,player_id,player_name,team_id,team_name,position,recipient_id,recipient_name,pass_length,pass_angle,pass_height,pass_type,start_x,start_y,end_x,end_y
0,3857276,05a57281-9295-408a-9c4f-e32d7fad4d96,6301,Youssef En-Nesyri,788,Morocco,Center Forward,5234.0,Sofyan Amrabat,12.557467,3.045886,Ground Pass,Kick Off,61.0,40.1,48.5,41.3
1,3857276,3a06bcce-1408-4a0b-be01-f6b93f142b30,5234,Sofyan Amrabat,788,Morocco,Center Defensive Midfield,12149.0,Nayef Aguerd,24.344608,2.396870,Ground Pass,NaN,48.4,42.5,30.5,59.0
2,3857276,1f1b0ef8-1a1d-45b3-bf9c-4299ea836377,12149,Nayef Aguerd,788,Morocco,Right Center Back,5219.0,Romain Saïss,32.118843,-1.605051,Ground Pass,NaN,30.9,59.0,29.8,26.9
3,3857276,84cdb79d-76e6-408a-bbc4-34026594624a,5219,Romain Saïss,788,Morocco,Left Center Back,12149.0,Nayef Aguerd,32.930990,1.781890,Ground Pass,NaN,31.7,26.2,24.8,58.4
4,3857276,28e07622-dd23-4af6-8439-cb9856c545db,12149,Nayef Aguerd,788,Morocco,Right Center Back,5245.0,Achraf Hakimi Mouh,20.077100,1.171791,Ground Pass,NaN,26.9,59.5,34.7,78.0

In [25]:
passes_df.shape

(955, 17)

In [26]:
passes_df.isna().sum()

match_id            0
event_id            0
player_id           0
player_name         0
team_id             0
team_name           0
position            0
recipient_id       86
recipient_name     86
pass_length         0
pass_angle          0
pass_height         0
pass_type         793
start_x             0
start_y             0
end_x               0
end_y               0
dtype: int64

In [27]:
passes_df[
    passes_df["recipient_id"].isna()
].head()

,match_id,event_id,player_id,player_name,team_id,team_name,position,recipient_id,recipient_name,pass_length,pass_angle,pass_height,pass_type,start_x,start_y,end_x,end_y
25,3857276,da5afb4a-b9a7-45e7-8381-a91d8d6df8ef,5237,Hakim Ziyech,788,Morocco,Right Wing,NaN,NaN,13.014223,-2.041317,Ground Pass,NaN,56.7,78.0,50.8,66.4
55,3857276,bcb74546-ede9-4c05-ae8c-1dd7e176f815,5219,Romain Saïss,788,Morocco,Left Center Back,NaN,NaN,59.300083,0.285480,High Pass,NaN,31.7,5.9,88.6,22.6
61,3857276,e5d4f6ca-6c95-4d85-a08e-c1383b31a983,11846,Steven de Sousa Vitoria,1833,Canada,Right Center Back,NaN,NaN,0.824621,0.244979,Low Pass,NaN,28.1,47.8,28.9,48.0
70,3857276,3b751a5c-9f21-49e4-b50e-d8d665df1cb9,15890,Noussair Mazraoui,788,Morocco,Left Back,NaN,NaN,21.434784,0.112203,Low Pass,NaN,43.3,8.9,64.6,11.3
75,3857276,1500b33a-292f-4236-a400-03272fa1deee,16459,Cyle Larin,1833,Canada,Center Forward,NaN,NaN,2.102380,-0.047583,Low Pass,NaN,45.7,76.9,47.8,76.8

In [28]:
passes_df["pass_type"].value_counts(dropna=False)

pass_type
NaN             793
Recovery         53
Throw-in         43
Free Kick        35
Goal Kick        11
Corner            8
Interception      7
Kick Off          5
Name: count, dtype: int64

¿De dónde vienen todos estos nulos?

In [29]:
nan_passes = passes_df[
    passes_df["recipient_id"].isna()
]

nan_passes.head()

,match_id,event_id,player_id,player_name,team_id,team_name,position,recipient_id,recipient_name,pass_length,pass_angle,pass_height,pass_type,start_x,start_y,end_x,end_y
25,3857276,da5afb4a-b9a7-45e7-8381-a91d8d6df8ef,5237,Hakim Ziyech,788,Morocco,Right Wing,NaN,NaN,13.014223,-2.041317,Ground Pass,NaN,56.7,78.0,50.8,66.4
55,3857276,bcb74546-ede9-4c05-ae8c-1dd7e176f815,5219,Romain Saïss,788,Morocco,Left Center Back,NaN,NaN,59.300083,0.285480,High Pass,NaN,31.7,5.9,88.6,22.6
61,3857276,e5d4f6ca-6c95-4d85-a08e-c1383b31a983,11846,Steven de Sousa Vitoria,1833,Canada,Right Center Back,NaN,NaN,0.824621,0.244979,Low Pass,NaN,28.1,47.8,28.9,48.0
70,3857276,3b751a5c-9f21-49e4-b50e-d8d665df1cb9,15890,Noussair Mazraoui,788,Morocco,Left Back,NaN,NaN,21.434784,0.112203,Low Pass,NaN,43.3,8.9,64.6,11.3
75,3857276,1500b33a-292f-4236-a400-03272fa1deee,16459,Cyle Larin,1833,Canada,Center Forward,NaN,NaN,2.102380,-0.047583,Low Pass,NaN,45.7,76.9,47.8,76.8

In [30]:
evento_id = nan_passes["event_id"].iloc[0]

In [31]:
for event in events:
    if event["id"] == evento_id:
        from pprint import pprint
        pprint(event)
        break

{'duration': 1.567809,
 'id': 'da5afb4a-b9a7-45e7-8381-a91d8d6df8ef',
 'index': 88,
 'location': [56.7, 78.0],
 'minute': 1,
 'pass': {'angle': -2.0413167,
          'body_part': {'id': 40, 'name': 'Right Foot'},
          'end_location': [50.8, 66.4],
          'height': {'id': 1, 'name': 'Ground Pass'},
          'length': 13.014223,
          'outcome': {'id': 9, 'name': 'Incomplete'}},
 'period': 1,
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'player': {'id': 5237, 'name': 'Hakim Ziyech'},
 'position': {'id': 17, 'name': 'Right Wing'},
 'possession': 5,
 'possession_team': {'id': 788, 'name': 'Morocco'},
 'related_events': ['ad028499-5baa-4f29-a498-6f170d8b6948'],
 'second': 53,
 'team': {'id': 788, 'name': 'Morocco'},
 'timestamp': '00:01:53.267',
 'type': {'id': 30, 'name': 'Pass'}}

Okay, a veces dice outcome en vez de recipient. Cuántos outcomes hay?

In [32]:
outcomes = []

for event in events:
    if event["type"]["name"] != "Pass":
        continue

    outcome = event["pass"].get("outcome", {}).get("name")

    outcomes.append(outcome)

pd.Series(outcomes).value_counts(dropna=False)

NaN             790
Incomplete      134
Out              21
Pass Offside      7
Unknown           3
Name: count, dtype: int64

In [33]:
pd.crosstab(
    passes_df["recipient_id"].isna(),
    pd.Series(outcomes).fillna("Complete")
)

col_0         Complete  Incomplete  Out  Pass Offside  Unknown
recipient_id
False              790          59   12             7        1
True                 0          75    9             0        2

¿Las intercepciones cómo figuran?

In [34]:
event_types = []

for event in events:
    event_types.append(event["type"]["name"])

pd.Series(event_types).value_counts()

Pass                 955
Ball Receipt*        868
Carry                782
Pressure             289
Ball Recovery         93
Duel                  63
Clearance             41
Dribble               39
Miscontrol            32
Foul Committed        31
Foul Won              31
Block                 27
Dispossessed          23
Dribbled Past         23
Interception          23
Goal Keeper           16
Shot                  12
Substitution          10
Tactical Shift         5
Half Start             4
Half End               4
Injury Stoppage        4
Referee Ball-Drop      4
Starting XI            2
50/50                  2
Error                  1
Shield                 1
Own Goal For           1
Own Goal Against       1
Offside                1
Name: count, dtype: int64

In [35]:
for event in events:
    if event["type"]["name"] == "Ball Receipt*":
        from pprint import pprint
        pprint(event)
        break

{'id': '1267faf9-e033-4985-925a-2f9521d63bc0',
 'index': 6,
 'location': [48.5, 41.3],
 'minute': 0,
 'period': 1,
 'play_pattern': {'id': 9, 'name': 'From Kick Off'},
 'player': {'id': 5234, 'name': 'Sofyan Amrabat'},
 'position': {'id': 10, 'name': 'Center Defensive Midfield'},
 'possession': 2,
 'possession_team': {'id': 788, 'name': 'Morocco'},
 'related_events': ['05a57281-9295-408a-9c4f-e32d7fad4d96'],
 'second': 1,
 'team': {'id': 788, 'name': 'Morocco'},
 'timestamp': '00:00:01.295',
 'type': {'id': 42, 'name': 'Ball Receipt*'}}

# Player Vector V.01

In [36]:
player_events = []

for event in events:

    if "player" not in event:
        continue

    player_events.append({
        "player_id": event["player"]["id"],
        "player_name": event["player"]["name"],
        "team_name": event["team"]["name"],
        "event_type": event["type"]["name"]
    })

player_events_df = pd.DataFrame(player_events)

player_events_df.head()

   player_id        player_name team_name     event_type
0       6301  Youssef En-Nesyri   Morocco           Pass
1       5234     Sofyan Amrabat   Morocco  Ball Receipt*
2       5234     Sofyan Amrabat   Morocco          Carry
3       5234     Sofyan Amrabat   Morocco           Pass
4      12149       Nayef Aguerd   Morocco  Ball Receipt*

In [37]:
player_events_df.shape

(3368, 4)

In [38]:
player_events_df["event_type"].value_counts()

event_type
Pass                955
Ball Receipt*       868
Carry               782
Pressure            289
Ball Recovery        93
Duel                 63
Clearance            41
Dribble              39
Miscontrol           32
Foul Committed       31
Foul Won             31
Block                27
Dispossessed         23
Dribbled Past        23
Interception         23
Goal Keeper          16
Shot                 12
Substitution         10
Injury Stoppage       4
50/50                 2
Error                 1
Shield                1
Own Goal Against      1
Offside               1
Name: count, dtype: int64

In [39]:
player_vector = (
    player_events_df
    .pivot_table(
        index=[
            "player_id",
            "player_name",
            "team_name"
        ],
        columns="event_type",
        values="event_type",
        aggfunc="count",
        fill_value=0
    )
    .reset_index()
)

In [40]:
player_vector.head()

event_type,player_id,player_name,team_name,50/50,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,...,Injury Stoppage,Interception,Miscontrol,Offside,Own Goal Against,Pass,Pressure,Shield,Shot,Substitution
0,3625,Sofiane Boufal,Morocco,0,27,2,2,22,0,1,...,0,1,3,0,0,18,24,0,1,1
1,3634,Abdelhamid Sabiri,Morocco,0,25,3,1,20,1,1,...,0,2,0,0,0,26,12,0,2,1
2,5219,Romain Saïss,Morocco,1,28,3,0,30,5,0,...,0,1,0,0,0,39,6,0,0,0
3,5234,Sofyan Amrabat,Morocco,0,38,4,0,39,3,1,...,0,2,0,0,0,47,22,0,0,0
4,5237,Hakim Ziyech,Morocco,0,34,4,2,36,1,1,...,0,1,1,0,0,40,18,0,2,1

In [41]:
player_vector.shape

(32, 27)

Reconstrucción en limpio

In [42]:
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [43]:
ADMIN_EVENTS = [
    "Starting XI",
    "Half Start",
    "Half End",
    "Substitution",
    "Tactical Shift",
    "Injury Stoppage",
    "Referee Ball-Drop",
]

player_events_clean = player_events_df[
    ~player_events_df["event_type"].isin(ADMIN_EVENTS)
].copy()

In [44]:
player_vector_v01 = (
    player_events_clean
    .pivot_table(
        index=["player_id", "player_name", "team_name"],
        columns="event_type",
        values="event_type",
        aggfunc="count",
        fill_value=0
    )
    .reset_index()
)

player_vector_v01.head()

event_type,player_id,player_name,team_name,50/50,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,...,Foul Won,Goal Keeper,Interception,Miscontrol,Offside,Own Goal Against,Pass,Pressure,Shield,Shot
0,3625,Sofiane Boufal,Morocco,0,27,2,2,22,0,1,...,4,0,1,3,0,0,18,24,0,1
1,3634,Abdelhamid Sabiri,Morocco,0,25,3,1,20,1,1,...,1,0,2,0,0,0,26,12,0,2
2,5219,Romain Saïss,Morocco,1,28,3,0,30,5,0,...,0,0,1,0,0,0,39,6,0,0
3,5234,Sofyan Amrabat,Morocco,0,38,4,0,39,3,1,...,1,0,2,0,0,0,47,22,0,0
4,5237,Hakim Ziyech,Morocco,0,34,4,2,36,1,1,...,0,0,1,1,0,0,40,18,0,2

Testeo los formatos esperados

In [45]:
# Test 1: no debería haber jugadores duplicados
assert player_vector_v01["player_id"].is_unique

# Test 2: no debería haber NaN
assert player_vector_v01.isna().sum().sum() == 0

# Test 3: debería haber jugadores de ambos equipos
assert player_vector_v01["team_name"].nunique() == 2

# Test 4: debería existir la columna Pass
assert "Pass" in player_vector_v01.columns

print("All tests passed")

All tests passed

Guardo de forma aislada un match

In [46]:
output_path = PROCESSED_DIR / f"player_vector_v01_match_{match_id}.csv"

player_vector_v01.to_csv(output_path, index=False)

print(output_path)

..\data\processed\player_vector_v01_match_3857276.csv

In [47]:
test_load = pd.read_csv(output_path)
test_load.head()

,player_id,player_name,team_name,50/50,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,...,Foul Won,Goal Keeper,Interception,Miscontrol,Offside,Own Goal Against,Pass,Pressure,Shield,Shot
0,3625,Sofiane Boufal,Morocco,0,27,2,2,22,0,1,...,4,0,1,3,0,0,18,24,0,1
1,3634,Abdelhamid Sabiri,Morocco,0,25,3,1,20,1,1,...,1,0,2,0,0,0,26,12,0,2
2,5219,Romain Saïss,Morocco,1,28,3,0,30,5,0,...,0,0,1,0,0,0,39,6,0,0
3,5234,Sofyan Amrabat,Morocco,0,38,4,0,39,3,1,...,1,0,2,0,0,0,47,22,0,0
4,5237,Hakim Ziyech,Morocco,0,34,4,2,36,1,1,...,0,0,1,1,0,0,40,18,0,2

## Testeo la primera función

In [48]:
def build_player_vector(events):

    # GENERO DF DE EVENTS
    player_events = []

    for event in events:

        if "player" not in event:
            continue

        player_events.append({
            "player_id": event["player"]["id"],
            "player_name": event["player"]["name"],
            "team_name": event["team"]["name"],
            "event_type": event["type"]["name"]
        })

    player_events_df = pd.DataFrame(player_events)

    # FILTRO EVENTOS ADMINISTRATIVOS
    ADMIN_EVENTS = [
        "Starting XI",
        "Half Start",
        "Half End",
        "Substitution",
        "Tactical Shift",
        "Injury Stoppage",
        "Referee Ball-Drop",
    ]

    player_events_clean = player_events_df[
        ~player_events_df["event_type"].isin(ADMIN_EVENTS)
    ].copy()

    # PLAYER VECTOR
    player_vector = (
        player_events_clean
        .pivot_table(
            index=[
                "player_id",
                "player_name",
                "team_name"
            ],
            columns="event_type",
            values="event_type",
            aggfunc="count",
            fill_value=0
        )
        .reset_index()
    )

    # TESTEO
    assert player_vector["player_id"].is_unique, "Hay jugadores duplicados"
    assert player_vector.isna().sum().sum() == 0, "Hay valores NaN"
    assert player_vector["team_name"].nunique() == 2, "No hay exactamente 2 equipos"
    assert "Pass" in player_vector.columns, "No existe la columna Pass"

    print("All tests passed")

    return player_vector

In [49]:
player_vector_test = build_player_vector(events)

player_vector_test.head()

All tests passed

event_type,player_id,player_name,team_name,50/50,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,...,Foul Won,Goal Keeper,Interception,Miscontrol,Offside,Own Goal Against,Pass,Pressure,Shield,Shot
0,3625,Sofiane Boufal,Morocco,0,27,2,2,22,0,1,...,4,0,1,3,0,0,18,24,0,1
1,3634,Abdelhamid Sabiri,Morocco,0,25,3,1,20,1,1,...,1,0,2,0,0,0,26,12,0,2
2,5219,Romain Saïss,Morocco,1,28,3,0,30,5,0,...,0,0,1,0,0,0,39,6,0,0
3,5234,Sofyan Amrabat,Morocco,0,38,4,0,39,3,1,...,1,0,2,0,0,0,47,22,0,0
4,5237,Hakim Ziyech,Morocco,0,34,4,2,36,1,1,...,0,0,1,1,0,0,40,18,0,2

## Genero función para todos los partidos

In [50]:
# Devuelve un json de cada partido

def load_events(match_id):
    event_file = EVENTS_DIR / f"{match_id}.json"

    with open(event_file, "r", encoding="utf-8") as f:
        events = json.load(f)

    return events

In [53]:
def build_worldcup_player_vector(matches_df, events_dir, save_path=None):
    """
    Construye un player vector acumulado para todos los partidos de un Mundial.

    Entrada:
    - matches_df: DataFrame con columna match_id
    - events_dir: carpeta donde están los events JSON
    - save_path: ruta opcional para guardar CSV

    Salida:
    - player_vector_worldcup: 1 fila por jugador en el torneo
    - player_vectors_match_level: 1 fila por jugador por partido
    """

    all_player_vectors = []

    for match_id in matches_df["match_id"]:

        event_file = events_dir / f"{match_id}.json"

        with open(event_file, "r", encoding="utf-8") as f:
            events = json.load(f)

        player_vector = build_player_vector(events)

        player_vector["match_id"] = match_id

        all_player_vectors.append(player_vector)

    # 1 fila por jugador por partido
    player_vectors_match_level = pd.concat(
    all_player_vectors,
    ignore_index=True
)


    # Columnas identificatorias
    id_cols = [
        "player_id",
        "player_name",
        "team_name"
    ]

    # Columnas numéricas/eventos
    numeric_cols = [
    col for col in player_vectors_match_level.select_dtypes(include="number").columns
    if col not in ["match_id", "player_id"]
    ]

    # 1 fila por jugador en todo el Mundial
    player_vector_worldcup = (
        player_vectors_match_level
        .groupby(id_cols)[numeric_cols]
        .sum()
        .reset_index()
    )

    # Tests básicos
    # assert player_vector_worldcup["player_id"].is_unique, "Hay jugadores duplicados"
    assert player_vector_worldcup.isna().sum().sum() == 0, "Hay valores NaN"
    assert "Pass" in player_vector_worldcup.columns, "No existe la columna Pass"

    print("World Cup player vector created successfully")
    print("Match-level shape:", player_vectors_match_level.shape)
    print("World Cup-level shape:", player_vector_worldcup.shape)

    if save_path is not None:
        player_vector_worldcup.to_csv(save_path, index=False)
        print("Saved to:", save_path)

    return player_vector_worldcup, player_vectors_match_level

## 2022

In [54]:
save_path_2022 = PROCESSED_DIR / "player_vector_v01_worldcup_2022.csv"

player_vector_2022, player_vectors_2022_match_level = build_worldcup_player_vector(
    matches_df=matches_2022,
    events_dir=EVENTS_DIR,
    save_path=save_path_2022
)

All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
World Cup player vector created successfully
Match-level shape: (1996, 29)
World Cup-level shape: (681, 28)
Saved to: ..\data\processed\player_vector_v01_worldcup_2022.csv

### Corrijo jugador duplicado para 2022

In [55]:
duplicated_players = player_vector_2022[
    player_vector_2022["player_id"].duplicated(keep=False)
].sort_values("player_id")

duplicated_players[
    ["player_id", "player_name", "team_name"]
]

event_type  player_id   player_name team_name
94               4354    Phil Foden   England
95               4354  Philip Foden   England

In [56]:
player_vectors_2022_match_level["player_name"] = (
    player_vectors_2022_match_level["player_name"]
    .replace({
        "Philip Foden": "Phil Foden"
    })
)

In [57]:
id_cols = ["player_id", "player_name", "team_name"]

numeric_cols = [
    col for col in player_vectors_2022_match_level.select_dtypes(include="number").columns
    if col not in ["match_id", "player_id"]
]

player_vector_2022 = (
    player_vectors_2022_match_level
    .groupby(id_cols)[numeric_cols]
    .sum()
    .reset_index()
)

In [58]:
assert player_vector_2022["player_id"].is_unique
assert player_vector_2022.isna().sum().sum() == 0
assert "Pass" in player_vector_2022.columns

save_path_2022 = PROCESSED_DIR / "player_vector_v01_worldcup_2022.csv"

player_vector_2022.to_csv(save_path_2022, index=False)

print("Saved:", save_path_2022)

Saved: ..\data\processed\player_vector_v01_worldcup_2022.csv

In [59]:
player_vector_2022.shape

(680, 28)

In [60]:
player_vector_2022.sort_values("Pass", ascending=False).head(10)

event_type,player_id,player_name,team_name,50/50,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,...,Miscontrol,Offside,Own Goal Against,Pass,Pressure,Shield,Shot,Player Off,Player On,Bad Behaviour
248,6765,Rodrigo Hernández Cascante,Spain,0.0,595,20,6,549,12,1,...,2,0.0,0.0,679,19,0.0,1,0.0,0.0,0.0
17,3090,Nicolás Hernán Otamendi,Argentina,0.0,475,28,8,445,34,0,...,1,0.0,0.0,565,54,1.0,1,0.0,0.0,2.0
278,7797,Rodrigo Javier De Paul,Argentina,4.0,538,37,8,461,4,5,...,11,0.0,0.0,563,111,1.0,7,1.0,1.0,0.0
149,5463,Luka Modrić,Croatia,3.0,488,39,5,458,2,9,...,8,0.0,0.0,549,115,0.0,7,0.0,0.0,1.0
150,5469,Marcelo Brozović,Croatia,4.0,472,34,18,440,8,8,...,5,0.0,0.0,529,96,1.0,5,0.0,0.0,0.0
536,33018,Joško Gvardiol,Croatia,1.0,425,35,13,422,43,2,...,1,0.0,0.0,510,77,1.0,2,0.0,0.0,0.0
569,38718,Enzo Fernandez,Argentina,4.0,434,31,7,381,13,7,...,3,0.0,1.0,470,107,0.0,9,0.0,0.0,0.0
330,10481,Aurélien Djani Tchouaméni,France,2.0,407,37,7,390,8,2,...,8,0.0,0.0,470,64,0.0,7,2.0,2.0,0.0
147,5456,Mateo Kovačić,Croatia,4.0,432,32,8,404,6,10,...,5,0.0,0.0,456,136,0.0,3,0.0,0.0,1.0
51,3471,Dejan Lovren,Croatia,1.0,387,11,8,357,36,0,...,2,0.0,0.0,454,37,0.0,4,0.0,0.0,0.0

In [61]:
player_vector_2022.sort_values("Shot", ascending=False).head(10)

event_type,player_id,player_name,team_name,50/50,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,...,Miscontrol,Offside,Own Goal Against,Pass,Pressure,Shield,Shot,Player Off,Player On,Bad Behaviour
160,5503,Lionel Andrés Messi Cuccittini,Argentina,0.0,484,34,4,391,1,30,...,15,1.0,0.0,371,89,0.0,34,1.0,1.0,1.0
6,3009,Kylian Mbappé Lottin,France,0.0,361,30,2,298,0,17,...,21,0.0,0.0,233,37,0.0,32,1.0,1.0,0.0
66,3604,Olivier Giroud,France,0.0,130,3,3,37,5,1,...,7,1.0,0.0,75,60,0.0,17,0.0,0.0,1.0
151,5474,Ivan Perišić,Croatia,1.0,322,22,12,227,11,4,...,20,0.0,0.0,304,98,3.0,16,1.0,1.0,0.0
346,11456,Lautaro Javier Martínez,Argentina,1.0,130,6,3,64,0,6,...,10,0.0,0.0,63,20,0.0,15,0.0,0.0,0.0
91,4320,Neymar da Silva Santos Junior,Brazil,1.0,191,13,6,169,0,12,...,7,0.0,0.0,156,24,0.0,12,0.0,0.0,0.0
335,10955,Harry Kane,England,0.0,182,12,5,105,5,4,...,11,0.0,0.0,97,31,0.0,12,1.0,1.0,0.0
402,16532,Daniel Olmo Carvajal,Spain,1.0,247,20,7,200,2,10,...,10,0.0,0.0,196,46,0.0,12,0.0,0.0,0.0
297,8400,Serge Gnabry,Germany,1.0,131,19,4,101,2,6,...,3,0.0,0.0,113,34,0.0,12,0.0,0.0,0.0
209,5668,Robert Lewandowski,Poland,0.0,188,12,5,95,9,10,...,16,0.0,0.0,91,39,0.0,12,0.0,0.0,0.0

## 2018

In [62]:
WC_2018_SEASON_ID = 3

matches_2018_path = (
    MATCHES_DIR 
    / str(WC_COMPETITION_ID) 
    / f"{WC_2018_SEASON_ID}.json"
)

matches_2018 = pd.read_json(matches_2018_path)

matches_2018.shape

(64, 18)

In [63]:
save_path_2018 = PROCESSED_DIR / "player_vector_v01_worldcup_2018.csv"

player_vector_2018, player_vectors_2018_match_level = build_worldcup_player_vector(
    matches_df=matches_2018,
    events_dir=EVENTS_DIR,
    save_path=save_path_2018
)

All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
All tests passed
World Cup player vector created successfully
Match-level shape: (1787, 30)
World Cup-level shape: (606, 29)
Saved to: ..\data\processed\player_vector_v01_worldcup_2018.csv

In [64]:
player_vector_2018.shape

(606, 29)

In [65]:
player_vector_2018.sort_values("Pass", ascending=False).head(10)

event_type,player_id,player_name,team_name,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,Dribble,...,Pass,Player Off,Player On,Pressure,Shot,Offside,Shield,Bad Behaviour,50/50,Camera On
243,5463,Luka Modrić,Croatia,446,49,5,425,0,6,19,...,527,0.0,0.0,121,12,0.0,0.0,0.0,0.0,0.0
169,5201,Sergio Ramos García,Spain,432,19,2,390,5,0,0,...,496,0.0,0.0,29,5,0.0,2.0,0.0,0.0,0.0
37,3244,John Stones,England,414,22,13,400,25,0,0,...,479,0.0,0.0,48,6,0.0,1.0,0.0,0.0,0.0
137,4926,Francisco Román Alarcón Suárez,Spain,506,14,5,459,0,7,41,...,475,0.0,0.0,79,10,0.0,0.0,0.0,0.0,0.0
604,20005,Toby Alderweireld,Belgium,389,19,11,372,18,0,0,...,446,0.0,0.0,47,5,0.0,0.0,0.0,0.0,0.0
56,3336,Harry Maguire,England,363,25,11,335,14,2,5,...,434,0.0,0.0,37,11,0.0,1.0,2.0,0.0,0.0
250,5470,Ivan Rakitić,Croatia,399,31,14,329,3,6,10,...,426,1.0,1.0,134,17,0.0,0.0,0.0,1.0,0.0
177,5211,Jordi Alba Ramos,Spain,382,17,8,314,2,1,5,...,414,0.0,0.0,63,2,1.0,0.0,0.0,1.0,0.0
51,3308,Kieran Trippier,England,274,19,19,236,9,3,8,...,393,1.0,1.0,140,4,0.0,0.0,0.0,0.0,0.0
32,3205,Kyle Walker,England,313,29,7,312,27,2,7,...,385,1.0,1.0,36,0,0.0,0.0,1.0,0.0,0.0

In [66]:
player_vector_2018.sort_values("Shot", ascending=False).head(10)

event_type,player_id,player_name,team_name,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,Dribble,...,Pass,Player Off,Player On,Pressure,Shot,Offside,Shield,Bad Behaviour,50/50,Camera On
124,4320,Neymar da Silva Santos Junior,Brazil,386,25,2,346,0,23,43,...,283,1.0,1.0,72,27,2.0,0.0,1.0,0.0,0.0
254,5474,Ivan Perišić,Croatia,307,12,10,169,5,7,6,...,209,0.0,0.0,136,24,0.0,1.0,0.0,0.0,0.0
72,3501,Philippe Coutinho Correia,Brazil,349,23,6,313,0,10,10,...,325,0.0,0.0,97,23,1.0,0.0,1.0,0.0,0.0
174,5207,Cristiano Ronaldo dos Santos Aveiro,Portugal,212,9,3,127,4,8,14,...,113,0.0,0.0,31,22,0.0,0.0,1.0,0.0,0.0
267,5487,Antoine Griezmann,France,298,26,6,218,3,7,14,...,248,0.0,0.0,172,21,0.0,0.0,0.0,2.0,0.0
283,5503,Lionel Andrés Messi Cuccittini,Argentina,280,22,7,251,0,16,28,...,202,0.0,0.0,66,18,0.0,0.0,1.0,1.0,0.0
93,3621,Eden Hazard,Belgium,363,23,7,322,1,13,42,...,271,0.0,0.0,99,18,0.0,0.0,0.0,0.0,0.0
250,5470,Ivan Rakitić,Croatia,399,31,14,329,3,6,10,...,426,1.0,1.0,134,17,0.0,0.0,0.0,1.0,0.0
46,3293,Jesse Lingard,England,297,23,7,217,2,5,11,...,228,0.0,0.0,161,16,0.0,0.0,0.0,0.0,0.0
123,4319,Edinson Roberto Cavani Gómez,Uruguay,149,13,4,90,2,5,11,...,83,1.0,1.0,80,16,0.0,0.0,0.0,1.0,0.0

## Guardo archivos de vectores 2018 y 2022

In [70]:
player_vector_2018.to_csv(
    processed_dir / "player_vector_2018.csv",
    index=False
)

player_vector_2022.to_csv(
    processed_dir / "player_vector_2022.csv",
    index=False
)

# Vector Histórico

In [67]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

processed_dir = BASE_DIR / "data" / "processed"
processed_dir

WindowsPath('c:/Users/Guido/Documents/Gui Archives/Coding/Mundial 2026/world-cup-predictor/data/processed')

In [71]:
player_vector_2018 = pd.read_csv(processed_dir / "player_vector_2018.csv")
player_vector_2022 = pd.read_csv(processed_dir / "player_vector_2022.csv")

player_vector_2018.shape, player_vector_2022.shape

((606, 29), (680, 28))

In [72]:
cols_2018 = set(player_vector_2018.columns)
cols_2022 = set(player_vector_2022.columns)

print("Solo 2018:")
print(sorted(cols_2018 - cols_2022))

print("\nSolo 2022:")
print(sorted(cols_2022 - cols_2018))

Solo 2018:
['Camera On']

Solo 2022:
[]

In [74]:
# Unifico esquema de columnas entre 2018 y 2022

all_columns = sorted(cols_2018 | cols_2022)

player_vector_2018_common = player_vector_2018.reindex(
    columns=all_columns,
    fill_value=0
)

player_vector_2022_common = player_vector_2022.reindex(
    columns=all_columns,
    fill_value=0
)

In [75]:
assert list(player_vector_2018_common.columns) == list(player_vector_2022_common.columns)

player_vector_2018_common.shape, player_vector_2022_common.shape

((606, 29), (680, 29))

In [76]:
player_historical_vector_v01 = pd.concat(
    [player_vector_2018_common, player_vector_2022_common],
    ignore_index=True
)

player_historical_vector_v01.shape

(1286, 29)

In [77]:
player_historical_vector_v01.to_csv(
    processed_dir / "player_historical_vector_v01.csv",
    index=False
)