# 11 - International Data Inventory

This notebook explores the international competitions available in the StatsBomb Open Data directory.

The goal is to identify which competitions can be used to build a more updated player database for the World Cup Predictor 2026 project.

# EDA

## Imports

In [2]:
import pandas as pd
from pathlib import Path

## Paths

In [6]:
BASE_DIR = Path("..")
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
STATSBOMB_DATA_DIR = RAW_DIR / "statsbomb" / "data"

## Load Competitions

In [7]:
competitions_path = STATSBOMB_DATA_DIR / "competitions.json"

competitions = pd.read_json(competitions_path)

competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

## Basic Inspections

In [8]:
competitions.shape

(80, 12)

In [9]:
competitions.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             80 non-null     int64
 1   season_id                  80 non-null     int64
 2   country_name               80 non-null     str
 3   competition_name           80 non-null     str
 4   competition_gender         80 non-null     str
 5   competition_youth          80 non-null     bool
 6   competition_international  80 non-null     bool
 7   season_name                80 non-null     str
 8   match_updated              80 non-null     str
 9   match_updated_360          58 non-null     str
 10  match_available_360        12 non-null     str
 11  match_available            80 non-null     str
dtypes: bool(2), int64(2), str(8)
memory usage: 6.5 KB

In [10]:
competitions.columns

Index(['competition_id', 'season_id', 'country_name', 'competition_name',
       'competition_gender', 'competition_youth', 'competition_international',
       'season_name', 'match_updated', 'match_updated_360',
       'match_available_360', 'match_available'],
      dtype='str')

## Clean Competitions Table

In [18]:
competition_cols = [
    "competition_id",
    "season_id",
    "country_name",
    "competition_name",
    "competition_gender",
    "competition_youth",
    "competition_international",
    "season_name",
    "match_available",
    "match_available_360",
    "match_updated",
    "match_updated_360",
]

available_cols = [col for col in competition_cols if col in competitions.columns]

competitions_clean = competitions[available_cols].copy()

competitions_clean.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_available,match_available_360,match_updated,match_updated_360
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,2024-05-19T11:11:14.192381,NaN
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,NaN,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,NaN,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694

## Filter international male competitions

In [19]:
international_male = competitions_clean[
    (competitions_clean["competition_gender"] == "male") &
    (competitions_clean["competition_international"] == True) &
    (competitions_clean["competition_youth"] == False)
].copy()

international_male.sort_values(
    by=["competition_name", "season_name"]
)

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_available,match_available_360,match_updated,match_updated_360
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396
21,223,282,South America,Copa America,male,False,True,2024,2026-05-13T12:24:48.807600,NaN,2026-05-13T12:24:48.807600,NaN
37,43,269,International,FIFA World Cup,male,False,True,1958,2026-05-04T02:02:41.853159,NaN,2026-05-04T02:02:41.853159,NaN
36,43,270,International,FIFA World Cup,male,False,True,1962,2026-05-04T02:05:35.653887,NaN,2026-05-04T02:05:35.653887,NaN
35,43,272,International,FIFA World Cup,male,False,True,1970,2026-05-04T02:09:10.916859,NaN,2026-05-04T02:09:10.916859,NaN
34,43,51,International,FIFA World Cup,male,False,True,1974,2026-05-15T02:20:43.439689,NaN,2026-05-15T02:20:43.439689,2021-06-13T16:17:31.694
33,43,54,International,FIFA World Cup,male,False,True,1986,2026-05-04T01:30:23.212111,NaN,2026-05-04T01:30:23.212111,2021-06-13T16:17:31.694
32,43,55,International,FIFA World Cup,male,False,True,1990,2023-06-28T10:58:20.137929,NaN,2023-06-28T10:58:20.137929,2021-06-12T16:17:31.694
31,43,3,International,FIFA World Cup,male,False,True,2018,2026-05-15T15:48:12.789440,NaN,2026-05-15T15:48:12.789440,2021-06-13T16:17:31.694
30,43,106,International,FIFA World Cup,male,False,True,2022,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717
74,55,43,Europe,UEFA Euro,male,False,True,2020,2026-05-10T12:59:26.302088,2026-05-10T13:00:25.564993,2026-05-10T12:59:26.302088,2026-05-10T13:00:25.564993
73,55,282,Europe,UEFA Euro,male,False,True,2024,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979

In [20]:
international_male["competition_name"].value_counts()

competition_name
FIFA World Cup            8
UEFA Euro                 2
African Cup of Nations    1
Copa America              1
Name: count, dtype: int64

## Count available international competitions

In [21]:
international_male[
    [
        "competition_id",
        "season_id",
        "competition_name",
        "season_name",
        "country_name",
        "match_available"
    ]
].sort_values(
    by=["competition_name", "season_name"]
)

,competition_id,season_id,competition_name,season_name,country_name,match_available
2,1267,107,African Cup of Nations,2023,Africa,2026-05-12T21:18:08.827431
21,223,282,Copa America,2024,South America,2026-05-13T12:24:48.807600
37,43,269,FIFA World Cup,1958,International,2026-05-04T02:02:41.853159
36,43,270,FIFA World Cup,1962,International,2026-05-04T02:05:35.653887
35,43,272,FIFA World Cup,1970,International,2026-05-04T02:09:10.916859
34,43,51,FIFA World Cup,1974,International,2026-05-15T02:20:43.439689
33,43,54,FIFA World Cup,1986,International,2026-05-04T01:30:23.212111
32,43,55,FIFA World Cup,1990,International,2023-06-28T10:58:20.137929
31,43,3,FIFA World Cup,2018,International,2026-05-15T15:48:12.789440
30,43,106,FIFA World Cup,2022,International,2026-05-04T01:48:57.914346
74,55,43,UEFA Euro,2020,Europe,2026-05-10T12:59:26.302088
73,55,282,UEFA Euro,2024,Europe,2026-05-01T19:54:25.846072

## Candidate competitions for V1 player database

In [22]:
candidate_keywords = [
    "FIFA World Cup",
    "Copa America",
    "UEFA Euro",
    "European Championship",
    "Asian Cup",
    "Africa Cup",
    "CONCACAF",
    "Gold Cup",
]

pattern = "|".join(candidate_keywords)

candidate_competitions = international_male[
    international_male["competition_name"].str.contains(
        pattern,
        case=False,
        na=False
    )
].copy()

candidate_competitions.sort_values(
    by=["competition_name", "season_name"]
)

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_available,match_available_360,match_updated,match_updated_360
21,223,282,South America,Copa America,male,False,True,2024,2026-05-13T12:24:48.807600,NaN,2026-05-13T12:24:48.807600,NaN
37,43,269,International,FIFA World Cup,male,False,True,1958,2026-05-04T02:02:41.853159,NaN,2026-05-04T02:02:41.853159,NaN
36,43,270,International,FIFA World Cup,male,False,True,1962,2026-05-04T02:05:35.653887,NaN,2026-05-04T02:05:35.653887,NaN
35,43,272,International,FIFA World Cup,male,False,True,1970,2026-05-04T02:09:10.916859,NaN,2026-05-04T02:09:10.916859,NaN
34,43,51,International,FIFA World Cup,male,False,True,1974,2026-05-15T02:20:43.439689,NaN,2026-05-15T02:20:43.439689,2021-06-13T16:17:31.694
33,43,54,International,FIFA World Cup,male,False,True,1986,2026-05-04T01:30:23.212111,NaN,2026-05-04T01:30:23.212111,2021-06-13T16:17:31.694
32,43,55,International,FIFA World Cup,male,False,True,1990,2023-06-28T10:58:20.137929,NaN,2023-06-28T10:58:20.137929,2021-06-12T16:17:31.694
31,43,3,International,FIFA World Cup,male,False,True,2018,2026-05-15T15:48:12.789440,NaN,2026-05-15T15:48:12.789440,2021-06-13T16:17:31.694
30,43,106,International,FIFA World Cup,male,False,True,2022,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717
74,55,43,Europe,UEFA Euro,male,False,True,2020,2026-05-10T12:59:26.302088,2026-05-10T13:00:25.564993,2026-05-10T12:59:26.302088,2026-05-10T13:00:25.564993
73,55,282,Europe,UEFA Euro,male,False,True,2024,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979,2026-05-01T19:54:25.846072,2026-05-01T19:58:06.077979

## Save inventory

In [23]:
output_path = DATA_DIR / "processed" / "international_competitions_inventory.csv"

candidate_competitions.to_csv(output_path, index=False)

output_path

WindowsPath('../data/processed/international_competitions_inventory.csv')

## Markdown First Close Up

### Initial Findings

This notebook explored the international male competitions available in the local StatsBomb Open Data directory.

The next step is to evaluate which of these competitions should be included in the first version of the updated player database.

For V1, the priority is not to expand the training dataset yet, but to improve the representation of current national teams by building updated player vectors from recent international competitions.

# Data Availability Check

In [25]:
from pathlib import Path

for _, row in candidate_competitions.iterrows():

    competition_id = row["competition_id"]
    season_id = row["season_id"]

    matches_file = (
        STATSBOMB_DATA_DIR /
        "matches" /
        str(competition_id) /
        f"{season_id}.json"
    )

    print(
        row["competition_name"],
        row["season_name"],
        matches_file.exists()
    )

Copa America 2024 True
FIFA World Cup 2022 True
FIFA World Cup 2018 True
FIFA World Cup 1990 True
FIFA World Cup 1986 True
FIFA World Cup 1974 True
FIFA World Cup 1970 True
FIFA World Cup 1962 True
FIFA World Cup 1958 True
UEFA Euro 2024 True
UEFA Euro 2020 True